on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install rust-toolchain
        run: rustc --version

      - name: cargo fetch --locked
        run: cargo fetch --locked

      - name: cargo check kernels
        run: cargo check -p collatz -p mandelbrot

      - name: cargo check runner
        run: cargo check -p runner
